import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import BackButton from './BackButton';
import Logo from './Logo';
import SiteFooter from './SiteFooter';
import {LayoutDashboard,FileText,UploadCloud,BarChart3,MessageSquare,UserRound,Settings,LogOut,Users,ClipboardList,Bell,Search,CheckCircle2,Clock3,ArrowRight} from 'lucide-react';
import {api} from '../lib/api';

export default function PortalShell({admin=false,children,user}){
 const nav=useNavigate(); const [open,setOpen]=useState(false); const [items,setItems]=useState([]); const wrap=useRef(null);
 const links=admin
  ? [['/admin','Dashboard',LayoutDashboard],['/admin/clients','Clients',Users],['/admin/requests','Requests',ClipboardList],['/admin/analysis','Analysis',BarChart3],['/admin/create-report','Create Report',UploadCloud],['/admin/reports','Reports',FileText],['/admin/messages','Messages',MessageSquare],['/admin/contact-inquiries','Contact Inquiries',ClipboardList],['/admin/profile','Profile',UserRound]]
  : [['/client','Dashboard',LayoutDashboard],['/client/requests','My Requests',FileText],['/client/submit','Submit Data',UploadCloud],['/client/reports','My Reports',BarChart3],['/client/messages','Messages',MessageSquare],['/client/profile','Profile',UserRound]];
 useEffect(()=>{let alive=true;api.requests().then(rs=>{if(!alive)return;const list=[];rs.slice(0,5).forEach(r=>{if(r.status&&r.status!=='New')list.push({id:`s-${r.id}`,title:admin?`${r.business_name} is ${r.status}`:`Your ${r.business_name} request is ${r.status}`,text:admin?'Open Requests to review the engagement.':'Open My Requests for the latest status.',href:admin?'/admin/requests':'/client/requests',type:'status'});(r.reports||[]).filter(x=>admin||x.sent_at).slice(-2).forEach(rep=>list.push({id:`r-${rep.id}`,title:admin?`Report ready: ${rep.title}`:`New report: ${rep.title}`,text:admin?'Open Reports to review or deliver it.':'Open My Reports to view your report.',href:admin?'/admin/reports':'/client/reports',type:'report'}));});setItems(list.slice(0,6))}).catch(()=>{});return()=>{alive=false}},[admin,user?.id]);
 useEffect(()=>{function close(e){if(wrap.current&&!wrap.current.contains(e.target))setOpen(false)}document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 return <div className="portal"><aside><Logo/><div className="portal-label">{admin?'ADMIN PORTAL':'CLIENT PORTAL'}</div>{links.map(([p,t,I])=><NavLink key={p} to={p} end={p==='/admin'||p==='/client'} className={({isActive})=>isActive?'portal-nav-item active':'portal-nav-item'}><I size={17}/><span>{t}</span></NavLink>)}<div className="side-bottom"><Link to={admin?'/admin/profile':'/client/profile'}><Settings size={18}/>Settings</Link><button onClick={()=>{localStorage.clear();nav('/')}}><LogOut size={18}/>Logout</button></div></aside>
  <main className="portal-main"><header><div className="search"><Search size={15}/><span>Search anything...</span></div><div className="notification-wrap" ref={wrap}><button className={`portal-notification ${open?'active':''}`} aria-label="Notifications" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Bell size={18}/>{items.length>0&&<i/>}</button>{open&&<div className="notification-panel"><div className="notification-head"><div><b>Notifications</b><small>{items.length?`${items.length} recent updates`:'You are all caught up'}</small></div><CheckCircle2 size={18}/></div>{items.length?items.map(x=><Link className="notification-item" to={x.href} onClick={()=>setOpen(false)} key={x.id}><span className="notification-icon">{x.type==='report'?<FileText size={15}/>:<Clock3 size={15}/>}</span><span><b>{x.title}</b><small>{x.text}</small></span><ArrowRight size={14}/></Link>):<div className="notification-empty"><CheckCircle2 size={22}/><b>No new notifications</b><span>New request and report updates will appear here.</span></div>}</div>}</div><div className="user-pill"><span className="avatar">{(user?.full_name||'U').slice(0,2).toUpperCase()}</span><div><b>{user?.full_name||'User'}</b><small>{admin?'Admin':'Client'}</small></div></div></header><div className="portal-content"><div className="portal-content-top"><BackButton fallback={admin?'/admin':'/client'}/></div>{children}</div><SiteFooter/></main></div>
}
