import {useEffect,useMemo,useState} from 'react';
import PortalShell from '../components/PortalShell';
import {api,download,openPdf} from '../lib/api';
import {ArrowUpRight,UploadCloud,Headphones,TrendingUp,WalletCards,Target,MessageSquare,BarChart3,FileText,ShieldCheck,Download,CheckCircle2,Clock3,ChevronRight,Building2,CircleDollarSign,Lightbulb,Send,Paperclip,Activity,LockKeyhole} from 'lucide-react';
import {Link} from 'react-router-dom';

const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const pct=n=>`${Number(n||0).toFixed(1)}%`;
const firstName=u=>(u?.full_name||'Client').split(' ')[0];

export default function Client({view='dashboard'}){
 const [user,setUser]=useState(JSON.parse(localStorage.getItem('finsight_user')||'null'));
 const [requests,setRequests]=useState([]); const [error,setError]=useState('');
 const refresh=()=>api.requests().then(setRequests).catch(e=>setError(e.message));
 useEffect(()=>{api.me().then(setUser).catch(()=>{});refresh()},[]);
 const shell=children=><PortalShell user={user}>{children}{error&&<div className="error page-message">{error}</div>}</PortalShell>;
 if(view==='submit')return shell(<Submit onCreated={refresh}/>);
 if(view==='requests')return shell(<ListPage requests={requests}/>);
 if(view==='reports')return shell(<Reports requests={requests}/>);
 if(view==='messages')return shell(<Messages requests={requests}/>);
 if(view==='profile')return shell(<Profile user={user}/>);
 return shell(<Dashboard user={user} requests={requests}/>);
}

function Dashboard({user,requests}){
 const latestRequest=requests[0]; const growth=latestRequest?.growth||[];
 const latest=growth.at(-1)||{}; const prev=growth.length>1?growth.at(-2):null;
 const revenueGrowth=prev?.revenue?((latest.revenue-prev.revenue)/prev.revenue*100):0;
 const profitGrowth=prev?.profit?((latest.profit-prev.profit)/prev.profit*100):0;
 const analysis=latestRequest?.summary||{};
 const reports=useMemo(()=>requests.flatMap(r=>(r.reports||[]).filter(x=>x.sent_at).map(x=>({...x,business:r.business_name,requestId:r.id}))).slice(0,4),[requests]);
 const active=requests.filter(x=>!['Completed','Report Ready'].includes(x.status)).length;
 return <section className="dash client-dashboard">
  <div className="dash-head client-welcome"><div><p className="eyebrow">CLIENT OVERVIEW</p><h1>Good Morning, {firstName(user)} <span className="wave">👋</span></h1><p>Your FinSight workspace for financial performance, reports and business decisions.</p></div><div className="welcome-actions"><Link className="btn" to="/client/submit"><UploadCloud size={16}/> Submit Data</Link><Link className="btn ghost" to="/client/reports"><FileText size={16}/> My Reports</Link></div></div>
  <div className="client-trust"><span><LockKeyhole size={14}/> Private client workspace</span><span><Activity size={14}/> Financial insights updated by FinSight</span><span>{latestRequest?.business_name||'No business added yet'}</span></div>
  <div className="kpis client-kpis">
   <K title="Revenue Growth" value={`${revenueGrowth>=0?'+':''}${pct(revenueGrowth)}`} text="vs previous period" icon={<TrendingUp/>} trend={revenueGrowth>=0}/>
   <K title="Net Profit" value={money(latest.profit||analysis.profit)} text="Latest reported period" icon={<WalletCards/>}/>
   <K title="Profit Margin" value={pct(latest.margin||analysis.margin)} text="Current profitability" icon={<Target/>}/>
   <K title="Active Requests" value={active} text="Being handled by FinSight" icon={<Activity/>}/>
  </div>
  <div className="client-main-grid">
   <div className="panel client-performance"><div className="panel-title"><div><p className="eyebrow">PERFORMANCE</p><h2>Business Growth</h2></div><Link to="/client/reports">View reports <ChevronRight size={14}/></Link></div>{growth.length?<GrowthChart data={growth}/>:<EmptyState icon={<BarChart3/>} title="Your performance chart is waiting" text="Once FinSight completes an analysis, your revenue and profit trends will appear here." action="Submit Data" href="/client/submit"/>}</div>
   <div className="client-insight-stack">
    <div className="panel client-business-card"><div className="section-icon"><Building2/></div><p className="eyebrow">BUSINESS SNAPSHOT</p><h2>{latestRequest?.business_name||'Your Business'}</h2><p>{latestRequest?.business_type||'Business profile'} · {latestRequest?.status||'No request submitted'}</p><div className="snapshot-row"><span>Revenue</span><b>{money(latest.revenue||analysis.revenue)}</b></div><div className="snapshot-row"><span>Profit growth</span><b className={profitGrowth>=0?'positive':'negative'}>{profitGrowth>=0?'+':''}{pct(profitGrowth)}</b></div></div>
    <div className="panel client-tip"><div className="section-icon"><Lightbulb/></div><div><p className="eyebrow">FIN SIGHT TIP</p><h3>Turn numbers into decisions</h3><p>Open your latest report to see what is driving costs and where your analyst recommends action.</p><Link to="/client/reports">Explore insights <ArrowUpRight size={14}/></Link></div></div>
   </div>
  </div>
  <div className="client-bottom-grid">
   <div className="panel"><div className="panel-title"><div><p className="eyebrow">REQUEST TRACKING</p><h2>Current Analysis</h2></div><Link to="/client/requests">View all <ChevronRight size={14}/></Link></div>{latestRequest?<RequestProgress request={latestRequest}/>:<EmptyState icon={<ClipboardIcon/>} title="No analysis request yet" text="Start by sharing your business data with the FinSight team." action="Start Request" href="/client/submit"/>}</div>
   <div className="panel"><div className="panel-title"><div><p className="eyebrow">DELIVERED</p><h2>Recent Reports</h2></div><Link to="/client/reports">View all <ChevronRight size={14}/></Link></div>{reports.length?reports.map(rep=><div className="client-report-mini" key={rep.id}><div className="client-report-mini-icon"><FileText size={17}/></div><div><b>{rep.title}</b><small>{rep.business} · {new Date(rep.sent_at).toLocaleDateString()}</small></div><button onClick={()=>download(`/reports/${rep.id}/download`,safeName(rep.title)+'.pdf')}><Download size={15}/></button></div>):<div className="empty compact">Your delivered reports will appear here.</div>}</div>
  </div>
 </section>
}
function K({title,value,text,icon,trend}){return <div className="kpi kpi-rich"><div className="kpi-icon">{icon}</div><small>{title}</small><strong>{value}</strong><span className={trend===false?'negative':''}>{text}</span></div>}
function GrowthChart({data}){const max=Math.max(...data.map(x=>Number(x.revenue)||0),1);return <div className="growth-chart client-growth"><div className="chart-y"><span>{money(max)}</span><span>{money(max*.66)}</span><span>{money(max*.33)}</span><span>₹0</span></div><div className="growth-bars">{data.map((x,i)=><div className="growth-col" key={i}><div className="growth-bar" style={{height:`${Math.max(10,(Number(x.revenue)||0)/max*100)}%`}}><i style={{height:`${Math.max(5,(Number(x.profit)||0)/Math.max(Number(x.revenue)||1,1)*100)}%`}}/></div><small>{x.month}</small></div>)}</div><div className="chart-legend"><span><i/> Revenue</span><span><i/> Profit contribution</span></div></div>}
function RequestProgress({request}){const states=['Submitted','Received','Review','Analysis','Internal','Ready'];const status=request.status||'';const active=status==='Completed'?6:status==='Report Ready'?6:status==='Internal Review'?5:status==='In Analysis'?4:status==='Received'?2:1;return <div className="request-progress-card"><div className="request-progress-head"><div><b>{request.business_name}</b><small>{request.business_type} · Submitted {new Date(request.created_at).toLocaleDateString()}</small></div><span className="status-pill">{status}</span></div><div className="progress-line">{states.map((s,i)=><div className={i<active?'done':''} key={s}><span>{i<active?'✓':i+1}</span><small>{s}</small></div>)}</div></div>}
function Submit({onCreated}){
 const [form,setForm]=useState({business_name:'',business_type:'',period_from:'',period_to:'',requested_areas:[],additional_info:''});
 const [files,setFiles]=useState([]); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const toggle=x=>setForm(prev=>({...prev,requested_areas:prev.requested_areas.includes(x)?prev.requested_areas.filter(a=>a!==x):[...prev.requested_areas,x]}));
 async function submit(e){e.preventDefault();setBusy(true);setMsg('');try{const r=await api.createRequest(form);if(files.length)await api.upload(r.id,files);setMsg('Request submitted successfully. Your FinSight team will review it.');setForm({business_name:'',business_type:'',period_from:'',period_to:'',requested_areas:[],additional_info:''});setFiles([]);onCreated?.()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const goals=[
  ['Revenue','Sales and income performance'],['Expenses','Cost breakdown and control'],['Profitability','Margins and profit growth'],
  ['Inventory','Stock levels and turnover'],['Cash Flow','Money inflow and outflow'],['Marketing Costs','Advertising and promotion spend'],
  ['Overall Performance','Complete business health']
 ];
 return <section className="dash submit-page">
  <div className="dash-head"><div><p className="eyebrow">CLIENT WORKSPACE</p><h1>Share your financial data</h1><p>Tell us what you want to understand. Your analyst will turn the data into a clear business report.</p></div><div className="secure-label"><ShieldCheck size={14}/> Secure upload</div></div>
  <div className="submit-steps"><Step n="01" title="Business" active/><Step n="02" title="Financial Data" active/><Step n="03" title="FinSight Analysis"/><Step n="04" title="Report Delivery"/></div>
  <form className="submit-modern" onSubmit={submit}>
   <div className="panel submit-panel"><div className="panel-title"><div><p className="eyebrow">01 · BUSINESS PROFILE</p><h2>Tell us about your business</h2></div></div>
    <div className="modern-form-grid">
     <label className="modern-field"><span>Business Name</span><input required value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})} placeholder="e.g. Patel Metal Works"/></label>
     <label className="modern-field"><span>Business Type</span><select required value={form.business_type} onChange={e=>setForm({...form,business_type:e.target.value})}><option value="">Select industry</option><option>Manufacturing</option><option>Retail</option><option>Restaurant</option><option>Distribution</option><option>Services</option><option>E-commerce</option><option>Other</option></select></label>
     <label className="modern-field"><span>Analysis From</span><input type="month" value={form.period_from} onChange={e=>setForm({...form,period_from:e.target.value})}/></label>
     <label className="modern-field"><span>Analysis To</span><input type="month" value={form.period_to} onChange={e=>setForm({...form,period_to:e.target.value})}/></label>
    </div>
   </div>
   <div className="panel submit-panel"><p className="eyebrow">02 · ANALYSIS GOALS</p><h2>What should FinSight focus on?</h2>
    <div className="modern-goal-grid">{goals.map(([name,desc])=>{const selected=form.requested_areas.includes(name);return <label className={`goal-card ${selected?'selected':''}`} key={name}>
      <input type="checkbox" checked={selected} onChange={()=>toggle(name)}/><span className="goal-card-content"><span className="goal-card-text"><strong>{name}</strong><small>{desc}</small></span><span className={`goal-check ${selected?'checked':''}`}>{selected&&<CheckCircle2 size={17}/>}</span></span>
    </label>})}</div>
    <label className="modern-field modern-notes"><span>Anything your analyst should know?</span><textarea value={form.additional_info} onChange={e=>setForm({...form,additional_info:e.target.value})} placeholder="Mention unusual expenses, targets, seasonal trends, concerns or specific questions..."/><small className="field-hint">Add anything that can help your analyst understand the business better.</small></label>
   </div>
   <div className="panel submit-panel"><p className="eyebrow">03 · FINANCIAL DATA</p><h2>Upload your files</h2><label className="drop modern-drop"><UploadCloud size={34}/><b>{files.length?`${files.length} file${files.length>1?'s':''} selected`:'Drop your financial files here'}</b><span>XLSX, XLSM, CSV or PDF · Max 20 MB each</span><input type="file" multiple accept=".csv,.xlsx,.xls,.xlsm,.pdf" onChange={e=>setFiles([...e.target.files])}/>{files.length>0&&<div className="selected-files">{files.map(f=><span key={f.name}><Paperclip size={13}/>{f.name}</span>)}</div>}</label></div>
   {msg&&<div className={msg.includes('successfully')?'success':'error'}>{msg}</div>}
   <button className="btn submit-main" disabled={busy}>{busy?'Submitting...':'Submit to FinSight →'}</button>
  </form>
 </section>
}
function Step({n,title,active}){return <div className={active?'active':''}><span>{n}</span><b>{title}</b></div>}
function ListPage({requests}){return <section className="dash"><div className="dash-head"><div><p className="eyebrow">CLIENT WORKSPACE</p><h1>My Requests</h1><p>Follow every analysis from the moment you submit data until your report is delivered.</p></div><Link className="btn" to="/client/submit"><UploadCloud size={16}/> New Request</Link></div><div className="request-summary"><SummaryBox label="Total Requests" value={requests.length} icon={<FileText/>}/><SummaryBox label="In Progress" value={requests.filter(r=>!['Completed','Report Ready'].includes(r.status)).length} icon={<Clock3/>}/><SummaryBox label="Reports Delivered" value={requests.reduce((n,r)=>n+(r.reports||[]).filter(x=>x.sent_at).length,0)} icon={<CheckCircle2/>}/></div><div className="panel request-list">{requests.length?requests.map(r=><div className="request-list-card" key={r.id}><div className="request-list-icon"><Building2/></div><div className="request-list-main"><div><b>{r.business_name}</b><small>{r.business_type} · {r.period_from||'—'} to {r.period_to||'—'}</small></div><span className="status-pill">{r.status}</span><small>{r.files?.length||0} file(s)</small></div><ChevronRight size={18}/></div>):<EmptyState icon={<FileText/>} title="No requests yet" text="Your analysis requests will be tracked here." action="Submit Data" href="/client/submit"/>}</div></section>}
function SummaryBox({label,value,icon}){return <div className="summary-box"><div>{icon}</div><small>{label}</small><b>{value}</b></div>}
function Reports({requests}){const reports=requests.flatMap(r=>(r.reports||[]).filter(rep=>rep.sent_at).map(rep=>({...rep,business:r.business_name,requestId:r.id,client:r.client_name,analysisPeriod:`${r.period_from||'—'} to ${r.period_to||'—'}`})));const[selected,setSelected]=useState(null);const[analysis,setAnalysis]=useState(null);const[loading,setLoading]=useState(false);async function open(rep){setSelected(rep);setLoading(true);try{setAnalysis(await api.analysis(rep.requestId))}catch{setAnalysis(null)}finally{setLoading(false)}}return <section className="dash client-reports-page"><div className="dash-head"><div><p className="eyebrow">CLIENT REPORT CENTER</p><h1>My Reports</h1><p>Your delivered financial insights, explained in a clear and practical way.</p></div><span className="secure-label"><ShieldCheck size={14}/> Secure & Confidential</span></div><div className="report-center-banner"><div><p className="eyebrow">YOUR FINANCIAL INSIGHT</p><h2>{reports.length?`${reports.length} report${reports.length>1?'s':''} delivered`:'Your first report is on the way'}</h2><p>Open any report to understand performance, major cost drivers and the actions recommended by your FinSight analyst.</p></div><div className="report-banner-metrics"><div><small>Delivered</small><b>{reports.length}</b></div><div><small>Available</small><b>PDF</b></div></div></div><div className="report-center-toolbar"><div className="report-search"><FileText size={16}/><input placeholder="Search your reports..."/></div><span>Only reports sent by FinSight are shown here.</span></div><div className="client-report-list enhanced">{reports.length?reports.map(rep=><div className="client-report-card" key={rep.id} role="button" tabIndex={0} onClick={()=>open(rep)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')open(rep)}}><div className="client-report-icon"><FileText/></div><div className="client-report-main"><div><b>{rep.title}</b><small>{rep.business} · {rep.analysisPeriod}</small><small>Delivered {new Date(rep.sent_at).toLocaleString()}</small></div><span className="delivery-badge"><CheckCircle2 size={14}/> Delivered</span></div><div className="report-card-actions"><span>View report <ArrowUpRight size={15}/></span><button type="button" onClick={e=>{e.stopPropagation();download(`/reports/${rep.id}/download`,safeName(rep.title)+'.pdf')}}><Download size={15}/></button></div></div>):<div className="panel empty"><h3>No delivered reports yet</h3><p>When your FinSight analyst sends a report, it will appear here.</p><Link className="btn" to="/client/messages">Ask FinSight a question →</Link></div>}</div>{selected&&<ReportModal report={selected} analysis={analysis} loading={loading} close={()=>setSelected(null)}/>}</section>}
function ReportModal({report,analysis,loading,close}){const margin=Number(analysis?.margin||0);const meaning=margin>=20?'Your business is showing a strong profit margin. The next opportunity is to protect that margin while continuing controlled growth.':margin>=10?'Your business is profitable, but there is room to improve the margin by controlling the largest cost areas and improving operating efficiency.':'Your margin is under pressure. The most important next step is to review costs, pricing and operational efficiency with your FinSight analyst.';return <div className="client-report-overlay" onClick={close}><div className="client-report-modal premium" onClick={e=>e.stopPropagation()}><div className="report-modal-head"><div><span className="eyebrow">FINSIGHT FINANCIAL REPORT</span><h2>{report.business}</h2><p>{report.title} · Delivered {new Date(report.sent_at).toLocaleString()}</p></div><button className="icon-close" onClick={close}>×</button></div>{loading?<div className="modal-loading"><div className="loading-ring"/><p>Loading your financial insight...</p></div>:<><div className="kpis"><K title="Revenue" value={money(analysis?.revenue)} text="Reported revenue" icon={<CircleDollarSign/>}/><K title="Expenses" value={money(analysis?.expenses)} text="Total costs" icon={<WalletCards/>}/><K title="Net Profit" value={money(analysis?.profit)} text="Reported profit" icon={<Target/>}/><K title="Margin" value={pct(analysis?.margin)} text="Profitability" icon={<BarChart3/>}/></div><div className="client-understand premium"><div className="section-icon"><Lightbulb/></div><div><p className="eyebrow">WHAT THIS MEANS</p><h3>In simple business terms</h3><p>{meaning}</p></div></div><div className="finding-grid">{(analysis?.findings||[]).map((x,i)=><div key={i}><ShieldCheck size={17}/><span>{x}</span></div>)}</div><div className="modal-actions"><button className="btn ghost" onClick={()=>openPdf(`/reports/${report.id}/download`)}><FileText size={16}/> Preview PDF</button><button className="btn" onClick={()=>download(`/reports/${report.id}/download`,safeName(report.title)+'.pdf')}><Download size={16}/> Download Full PDF</button><Link className="btn ghost" to="/client/messages"><MessageSquare size={16}/> Ask Analyst</Link></div></>}</div></div>}
function Messages({requests}){const [rid,setRid]=useState(null);const [items,setItems]=useState([]);const [body,setBody]=useState('');const [msg,setMsg]=useState('');useEffect(()=>{if(!rid&&requests.length)setRid(requests[0].id)},[requests,rid]);useEffect(()=>{if(!rid)return;api.messages(rid).then(setItems).catch(e=>setMsg(e.message))},[rid]);async function send(){if(!body.trim()||!rid)return;try{const m=await api.sendMessage(rid,body.trim());setItems(p=>[...p,m]);setBody('')}catch(e){setMsg(e.message)}}return <section className="dash"><div className="dash-head"><div><p className="eyebrow">CLIENT COMMUNICATION</p><h1>Ask FinSight</h1><p>Talk directly with your analyst about your data, recommendations or delivered report.</p></div><span className="secure-label"><LockKeyhole size={14}/> Private conversation</span></div><div className="message-layout upgraded"><div className="panel"><div className="panel-title"><h3>Your Businesses</h3><span>{requests.length}</span></div>{requests.length?requests.map(r=><button className={`message-thread ${rid===r.id?'selected':''}`} key={r.id} onClick={()=>setRid(r.id)}><div className="thread-icon"><Building2 size={16}/></div><div><b>{r.business_name}</b><span>{r.status}</span><small>Request #{r.id}</small></div><ChevronRight size={15}/></button>):<div className="empty">Submit a request first.</div>}</div><div className="panel chat premium-chat">{rid?<><div className="chat-header"><div className="analyst-avatar"><ShieldCheck size={18}/></div><div><b>FinSight Analyst</b><small>{requests.find(r=>r.id===rid)?.business_name} · Available for questions</small></div></div><div className="chat-list">{items.length?items.map(m=><div className={m.sender_id===JSON.parse(localStorage.getItem('finsight_user')||'{}').id?'bubble mine':'bubble'} key={m.id}><b>{m.sender_name}</b><span>{m.body}</span><small>{new Date(m.created_at).toLocaleString()}</small></div>):<div className="chat-empty"><MessageSquare size={25}/><b>Start a conversation</b><span>Ask anything about your analysis or report.</span></div>}</div><div className="chat-input"><input value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask your analyst a question..."/><button className="btn" onClick={send}><Send size={15}/> Send</button></div></>:<div className="empty">Select a business to start.</div>}{msg&&<div className="error">{msg}</div>}</div></div></section>}
function Profile({user}){return <section className="dash"><div className="dash-head"><div><p className="eyebrow">CLIENT ACCOUNT</p><h1>Your Profile</h1><p>Manage your FinSight identity and business information.</p></div><span className="secure-label"><ShieldCheck size={14}/> Verified workspace</span></div><div className="profile-modern"><div className="panel profile-hero-card"><div className="profile-avatar large">{(user?.full_name||'U').slice(0,2).toUpperCase()}</div><p className="eyebrow">CLIENT ACCOUNT</p><h2>{user?.full_name||'—'}</h2><p>{user?.email||'—'}</p><span className="account-badge">Client</span></div><div className="panel"><p className="eyebrow">ACCOUNT DETAILS</p><div className="profile-grid modern"><div><small>Full Name</small><b>{user?.full_name||'—'}</b></div><div><small>Username</small><b>{user?.username||'—'}</b></div><div><small>Email</small><b>{user?.email||'—'}</b></div><div><small>Business</small><b>{user?.business_name||'—'}</b></div><div><small>Business Type</small><b>{user?.business_type||'—'}</b></div><div><small>Access</small><b>Client Portal</b></div></div></div></div></section>}
function EmptyState({icon,title,text,action,href}){return <div className="empty-state">{icon}<h3>{title}</h3><p>{text}</p>{action&&<Link className="btn ghost" to={href}>{action} <ArrowUpRight size={14}/></Link>}</div>}
function ClipboardIcon(){return <FileText size={28}/>}
function safeName(s){return String(s||'FinSight_Report').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')}
